/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#ffb4a3",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#f3f0ef",
        "primary-fixed": "#dae2ff",
        "surface-dim": "#dcd9d9",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#b2c5ff",
        "on-secondary-fixed": "#3d0600",
        "background": "#fcf9f8",
        "on-secondary-fixed-variant": "#8b1a00",
        "outline": "#737785",
        "surface-tint": "#0056d2",
        "surface-variant": "#e5e2e1",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#ffb59b",
        "on-tertiary-container": "#ffcebd",
        "on-surface": "#1b1b1c",
        "on-error": "#ffffff",
        "surface": "#fcf9f8",
        "surface-container-low": "#f6f3f2",
        "on-primary-fixed": "#001847",
        "inverse-primary": "#b2c5ff",
        "tertiary": "#822800",
        "on-tertiary-fixed": "#380d00",
        "error-container": "#ffdad6",
        "secondary-fixed": "#ffdad2",
        "secondary": "#b42907",
        "surface-container-highest": "#e5e2e1",
        "outline-variant": "#c3c6d6",
        "surface-bright": "#fcf9f8",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#424654",
        "on-tertiary-fixed-variant": "#812800",
        "on-background": "#1b1b1c",
        "surface-container": "#f0eded",
        "tertiary-container": "#a93802",
        "on-secondary-container": "#5b0d00",
        "on-primary-container": "#ccd8ff",
        "surface-container-high": "#eae7e7",
        "tertiary-fixed": "#ffdbcf",
        "primary-container": "#0056d2",
        "secondary-container": "#fe5d39",
        "on-secondary": "#ffffff",
        "inverse-surface": "#303030",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#0040a1",
        "primary": "#0040a1"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        'body-sm': ['IBM Plex Sans Arabic', 'sans-serif'],
        'body-md': ['IBM Plex Sans Arabic', 'sans-serif'],
        'body-lg': ['IBM Plex Sans Arabic', 'sans-serif'],
        'label-sm': ['IBM Plex Sans Arabic', 'sans-serif'],
        'label-md': ['IBM Plex Sans Arabic', 'sans-serif'],
        'label-lg': ['IBM Plex Sans Arabic', 'sans-serif'],
        'title-sm': ['IBM Plex Sans Arabic', 'sans-serif'],
        'title-md': ['IBM Plex Sans Arabic', 'sans-serif'],
        'title-lg': ['IBM Plex Sans Arabic', 'sans-serif'],
        'headline-sm': ['IBM Plex Sans Arabic', 'sans-serif'],
        'headline-md': ['IBM Plex Sans Arabic', 'sans-serif'],
        'headline-lg-mobile': ['IBM Plex Sans Arabic', 'sans-serif'],
        'display-sm': ['IBM Plex Sans Arabic', 'sans-serif'],
        'display-md': ['IBM Plex Sans Arabic', 'sans-serif'],
        'display-lg': ['IBM Plex Sans Arabic', 'sans-serif'],
      },
      spacing: {
        "section-gap": "80px",
        "margin-desktop": "64px",
        "container-max": "1280px",
        "gutter": "24px",
        "margin-mobile": "20px",
        "unit": "8px"
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
