async function testPiped() {
  const instances = [
    'https://pipedapi.kavin.rocks',
    'https://pipedapi.tokhmi.xyz',
    'https://api.piped.projectsegfau.lt',
    'https://piped-api.garudalinux.org'
  ];
  const videoId = 'koZiIO7nyl0';
  
  for (const instance of instances) {
    try {
      console.log("Trying:", instance);
      const res = await fetch(`${instance}/streams/${videoId}`);
      if (!res.ok) continue;
      const data = await res.json();
      const subtitles = data.subtitles;
      if (subtitles && subtitles.length > 0) {
        const vttUrl = subtitles.find(s => s.autoGenerated)?.url || subtitles[0].url;
        const vttRes = await fetch(vttUrl);
        const vttText = await vttRes.text();
        console.log("Success with:", instance);
        console.log("Transcript length:", vttText.length);
        return;
      }
    } catch(e) {
      console.error("Failed:", instance, e.message);
    }
  }
  console.log("All failed.");
}
testPiped();
